apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: halloworld-gateway
  namespace: hyf
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: halloworld
spec:
  hosts:
    - "*"
  gateways:
    - halloworld-gateway
  http:
    - match:
        - uri:
exact: /hallo
route:
- destination:
host: hallo
port:
  number: 5000